# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-11 18:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_libuser_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libitem',
            name='date_acquired',
            field=models.DateField(default=datetime.date(2016, 6, 11)),
        ),
    ]
