# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-14 14:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_suggestion_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='title',
            field=models.CharField(default=datetime.datetime(2016, 6, 14, 14, 38, 17, 806429, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
    ]
