# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-22 05:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20160615_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='libuser',
            name='profilepic',
            field=models.ImageField(default='/app/static/ProfilePics/defaultpic.png', max_length=10000, upload_to=''),
        ),
        migrations.AlterField(
            model_name='libitem',
            name='date_acquired',
            field=models.DateField(default=datetime.date(2016, 6, 22)),
        ),
    ]
