# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-22 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20160622_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libuser',
            name='profilepic',
            field=models.ImageField(default='/app/static/ProfilePics/defaultpic.png', max_length=10000, upload_to='/app/static/ProfilePics/'),
        ),
    ]
