# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-22 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20160622_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libuser',
            name='profilepic',
            field=models.FileField(default='/app/static/ProfilePics/defaultpic.png', upload_to='app/static/ProfilePics/'),
        ),
    ]
