# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 05:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20160626_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libitem',
            name='date_acquired',
            field=models.DateField(default=datetime.date(2016, 6, 27)),
        ),
        migrations.AlterField(
            model_name='libuser',
            name='profilepic',
            field=models.ImageField(default='app/static/Profilepics/defaultpic.png', upload_to='app/static/ProfilePics/'),
        ),
    ]
